from ._enum_compat import StrEnum


class SemanticState(StrEnum):
    ABORTED_BY_PEER = 'aborted_by_peer'
    ACCEPTED_BY_RUNTIME = 'accepted_by_runtime'
    ACKNOWLEDGED = 'acknowledged'
    CLOSED = 'closed'
    CLOSING = 'closing'
    COMPLETED = 'completed'
    CONGESTED = 'congested'
    DRAINING = 'draining'
    FAILED = 'failed'
    FAILED_DURING_EMIT = 'failed_during_emit'
    FLUSHED_TO_TRANSPORT = 'flushed_to_transport'
    GRACEFUL = 'graceful'
    IGNORED = 'ignored'
    INITIALIZED = 'initialized'
    LOST = 'lost'
    OPEN = 'open'
    OPENING = 'opening'
    PEER_ACKNOWLEDGED = 'peer_acknowledged'
    PEER_RESET = 'peer_reset'
    PROPAGATED = 'propagated'
    PROTOCOL_ERROR = 'protocol_error'
    QUEUED_FOR_TRANSPORT = 'queued_for_transport'
    READ_CLOSED = 'read_closed'
    REQUESTED = 'requested'
    RESUMED = 'resumed'
    SATURATED = 'saturated'
    SERVER_SHUTDOWN = 'server_shutdown'
    TIMEOUT = 'timeout'
    TRANSPORT_LOST = 'transport_lost'
    WRITABLE = 'writable'
    WRITE_CLOSED = 'write_closed'
