from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CONTRACT = ROOT / "contract"
SERDE_VERSION = 1
SCHEMA_DRAFT = "2020-12"


def compatibility_yaml(version: str) -> str:
    return (
        "# Generated by tools/build_compatibility.py; do not edit directly.\n"
        "contract_name: tigr-asgi-contract\n"
        f"contract_version: {version}\n"
        f"serde_version: {SERDE_VERSION}\n"
        f"schema_draft: {SCHEMA_DRAFT}\n"
    )


def main() -> None:
    version = (ROOT / "VERSION").read_text(encoding="utf-8").strip()
    (CONTRACT / "compatibility.yaml").write_text(
        compatibility_yaml(version),
        encoding="utf-8",
    )


if __name__ == "__main__":
    main()
